# When we specify the definition of a ReplicaSet we don't need to specify
# the definition of a pod because the template field in the ReplicaSet
# will act as a template to create the pods.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  # Template for the pods. All pods will be created using this template.
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue

spec:
  containers:
    - name: queue
      image: richardchesterwood/k8s-fleetman-queue:release1
