apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue

spec:
  selector:
    app: queue

  ports:
    - name: http
      port: 8161
      nodePort: 30010

    - name: endpoint
      port: 61616
      # This port will not be opened to outside the cluster, so no nodePort needed here

  # This Service is NodePort so that we can access the admin console (http) from the browser (outside of the cluster)
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker

spec:
  selector:
    app: position-tracker

  ports:
    - name: http
      port: 8080

  # We use ClusterIP because this service will be accessed from inside the cluster, the gateway service
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway

spec:
  selector:
    app: api-gateway

  ports:
    - name: http
      port: 8080

  # We use ClusterIP because this service will be accessed from inside the cluster, the webapp
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  selector:
    app: webapp

  ports:
    - name: http
      port: 80
      nodePort: 30080

  # This Service is NodePort so that we can access the webapp through the browser
  type: NodePort
