# What do we want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: mylocalstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
# How do we want it implemented?
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  # There are a lot of options to chose for volumes. hostPath is to store on the host.
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#volume-v1-core
  hostPath:
    # The host path where the data will be persisted
    path: /mnt/some_new/directory/structure/
    # If nothing exists at the given path, an empty directory will be created there
    type: DirectoryOrCreate
