# This Secret is just an example. It's values are not used by any container
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
data:
  accessKey: MTIzNDU2Nzg5MAo=
  secretKey: U0VDUkVUMTIzNAo=
