apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job
spec: # CronJob
  schedule: "* * * * *" # Run at every minute
  jobTemplate:
    spec: # Job
      template:
        spec: # Pod
          containers:
            - name: long-job
              image: python:alpine
              command: ["python"]
              args:
                [
                  "-c",
                  "import time; print('starting'); time.sleep(30); print('done');",
                ]
          restartPolicy: Never
      backoffLimit: 2
